# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=32)),
                ('album_title', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=32)),
                ('album_logo', models.FileField(upload_to='')),
                ('isfavorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=32)),
                ('audio_file', models.FileField(upload_to='')),
                ('isfavorite', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
    ]
